#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Prince Jain

# Short bio or description (displayed in the header)
description: Forever Curious

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/75776873?s=400&u=5a4092d6327021ef2d5db7030d3f3f61a338f7e7&v=4
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: prince.j19@fms.edu
  facebook: prince.jain.17
  flickr:
  github:
  linkedin: princejain17
  instagram: prince.jain.17
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: Prince_Jain17
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-WZLF9K3MJB

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://product-noob.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME




# # Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely edit after that. If you find
# # yourself editing this file very often, consider using Jekyll's data files
# # feature for the data you need to update frequently.
# #
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# #
# # If you need help with YAML syntax, here are some quick references for you: 
# # https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# # https://learnxinyminutes.com/docs/yaml/
# #
# # Site settings
# # These are used to personalize your new site. If you look in the HTML files,
# # you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# # You can create any custom variable you would like, and they will be accessible
# # in the templates via {{ site.myvariable }}.

# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# # Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# # Exclude from processing.
# # The following items will not be processed, by default.
# # Any item listed under the `exclude:` key here will be automatically added to
# # the internal "default list".
# #
# # Excluded items can be processed by explicitly listing the directories or
# # their entries' file path in the `include:` list.
# #
# # exclude:
# #   - .sass-cache/
# #   - .jekyll-cache/
# #   - gemfiles/
# #   - Gemfile
# #   - Gemfile.lock
# #   - node_modules/
# #   - vendor/bundle/
# #   - vendor/cache/
# #   - vendor/gems/
# #   - vendor/ruby/
